services:
  ocr:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sa.json
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      DOCAI_LOCATION: ${DOCAI_LOCATION}
      DOCAI_PROCESSOR_ID: ${DOCAI_PROCESSOR_ID}
      FILE_NAME: ${FILE_NAME}
    volumes:
      - ./secrets:/secrets:ro
      - ./input:/input:ro
