services:
  ocr:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    env_file: ../.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sa.json
    volumes:
      - ../secrets:/secrets:ro
      - ../input:/input:ro
