services:
  ocr:
    build:
      context: ../../..
      dockerfile: packages/cli/docker/Dockerfile.prod
    env_file: ../../../.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/sa.json
    volumes:
      - ../../../secrets:/app/secrets:ro
      - ../../../input:/app/input:ro
